services:
  fin_chatbot:
    build: .
    container_name: fin_chatbot
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - FETCH_INTERVAL_HOURS=${FETCH_INTERVAL_HOURS}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - METRICS_PORT=${METRICS_PORT}
    depends_on:
      - redis
      - postgres
    volumes:
      - ./logs:/var/log
    ports:
      - "${METRICS_PORT}:${METRICS_PORT}"
    healthcheck:
      test: ["CMD", "python", "-c", "import redis; redis.Redis(host='redis').ping()"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:6 
    container_name: fin_chatbot_redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:13
    container_name: fin_chatbot_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  redis_data:
  postgres_data: